name: Build
on:
  push:
    branches:
      - testdeploy
  pull_request:
    types: [opened, synchronize, reopened]
env:
  SRC_PATH: "src/dms-backend-api"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SonarScanner for .NET 5 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        # The key of the SonarQube project
        sonarProjectKey: "DMSGroupDev_dms"
        # The name of the SonarQube project
        sonarProjectName: "dms"
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        sonarOrganization: "dmsgroupdev"
        # Optional command arguments to dotnet build
        dotnetBuildArguments: ./src/dms-backend-api
        
        
        
